### ISSUE TITLE
Move off Travis CI?

### ISSUE THREAD

**Issue by oniofchaos** [devise-security/devise-security#102]
https://news.ycombinator.com/item?id=19218036

Based on this, it seems like a possible good long term move to get off the platform and use something more maintained. Thoughts @devise-security/maintainers ?

**Comment by natebird** [comment]
I’m a fan of CircleCI but it is a pain to migrate.

**Comment by seanfcarroll** [comment]
GitLab is free for open source.

**Comment by fidalgo** [comment]
You have github actions as alternative.
