### ISSUE TITLE
How to know :password_expirable and :password_archivable is working?

### ISSUE THREAD

**Issue by pepetorres1998** [devise-security/devise-security#129]
Hi, so I have included the 'devise-security' gem to my project. I have enabled the :password_expirable and :password_archivable, and I will attach my configuration of devise-security.

![Screenshot from 2019-08-28 17-15-59](https://user-images.githubusercontent.com/36722374/63896409-8d664a00-c9b7-11e9-999c-2af550e9e90c.png)

My question is how can I test, or how can I be sure that it is working?

I've been trying in the rails console to run `user.password_expire` and `user.password_expire!` without success, because I still can sign_in in Postman with the same password, and also the password_changed_at doesn't update.

If someone could help me or guide me to test with rspec the functionality, or with knowing how to reproduce the functionality of expire a password.

Thanks in advance!

Edit: The project is an API only.

**Comment by olbrich** [comment]
Assuming that your user model actually uses the correct modules, try calling `user.password_expiration_enabled?`.  Also, what version of active_support and/or rails are you using?

**Comment by pepetorres1998** [comment]
![Screenshot from 2019-08-29 14-02-14](https://user-images.githubusercontent.com/36722374/63968785-0f14b100-ca66-11e9-95b5-a2c730367747.png)

ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
Rails 5.2.3

**Comment by olbrich** [comment]
The tests that describe the behavior are in `test/test_password_expirable.rb`.  Password expirable compares the `password_changed_at` attribute on your User model to see if it's older than the allowable time.

`User#need_changed_password?` will also be true if the password is too old, or if the `password_changed_at` attribute is `nil`.

The whole thing won't work unless the feature is enabled, which you can check by using `User.send(:password_expiration_enabled?)`

Hopefully that gives you enough to get unstuck if you haven't already.

**Comment by pepetorres1998** [comment]
Thank you, that test of password expirable has helped me a lot, I still have the doubt of how it works, we have a controller for our devise auth sessions, we have to manually handle what to do when the password is expired?, or by default the gem sends email or something else so the user can change the password? Thank you in advance!

**Comment by pepetorres1998** [comment]
I leave a code snippet of our auth sessions controller.

![Screenshot from 2019-09-02 13-09-30](https://user-images.githubusercontent.com/36722374/64129632-edc40580-cd82-11e9-87cb-9adeabf6a065.png)

**Comment by oniofchaos** [comment]
You can see here:
https://github.com/devise-security/devise-security/blob/5f06e98907aa93a2ebd190a82725b261bdf7f091/lib/devise-security/hooks/password_expirable.rb#L3

and here:
https://github.com/devise-security/devise-security/blob/5f06e98907aa93a2ebd190a82725b261bdf7f091/lib/devise-security/controllers/helpers.rb#L50

what happens when using Devise for everything and there's a password expiration error. 

Since you're writing your own controller, you'll either need to use these hooks or manually check for this sort of thing and write your own logic to handle it.

**Comment by oniofchaos** [comment]
In terms of testing this, I would use [this](https://api.rubyonrails.org/v5.2.3/classes/ActiveSupport/Testing/TimeHelpers.html#method-i-travel) API to create the user's password in the past
```ruby
travel_to 1.year.ago do
  user = create(:user)
end

response = post :create, { user: user }

expect(response).to include(password_reset_message)
```
