### ISSUE TITLE
Customize redirect route

### ISSUE THREAD

**Issue by MasterBroki** [devise-security/devise-security#144]
Hi,

Is there a way to customize the redirection for expired password or deactivate it?

If so, could we document it a bit? thanks

**Comment by MasterBroki** [comment]
After some research in the source code, I need to override the redirect_for_password_change(scope) method in the base controller. Can we add this in the wiki so it helps someone else at some point?

**Comment by markblasdls** [comment]
@MasterBroki Hi, can you share how did you solve it with redirect_for_password_change? I'm currently having problem with redirect and can't override it. Thankyou in advance.

**Comment by MasterBroki** [comment]
@markblasdls  overriding it didn't work?

**Comment by markblasdls** [comment]
@MasterBroki yeah it didn't work for me but was able to find other way by modifying store_location_for(scope) and it solve my problem.. btw thankyou for your response.

**Comment by MasterBroki** [comment]
Maybe you're on a different version. Anyway, this needs more doc
