### ISSUE TITLE
[Code Question] Deciding if new password is in old password archive

### ISSUE THREAD

**Issue by andyklimczak** [devise-security/devise-security#15]
Hey, quick question about the code here in [password_archivable.rb#L30](https://github.com/devise-security/devise-security/blob/master/lib/devise-security/models/password_archivable.rb#L30)

We're looping through the old passwords in the archive, creating a `dummy` resource and setting the encrypted password to each old password, then trying to login with the `new` password. If a login succeeds (`valid_login?` is true) then that means the `new` password is in the password archive and cannot be used, and if all logins fail (not valid) then the password is not in the archive and can be used.

My question is, why create a new `dummy` instead of hashing the `new` password and checking if `hashed_new_password` is in the set of `old_passwords`?

I'm not trying to criticize the code, but gain a understanding of what `valid_login?` gives us that a set/array includes? check does not.

**Comment by oniofchaos** [comment]
Hey @andyklimczak, we're a fork of an older project so unfortunately we don't have a deep understanding of the code decisions that were made like this one. If you feel like you can refactor this to be more performant by all means make a PR - just be sure to include benchmarking to demonstrate the improvement.

**Comment by andyklimczak** [comment]
Totally understand, and perhaps I will!

I was interested to see if anyone had any insight is all

**Comment by andyklimczak** [comment]
So now I understand a bit more, devise doesn't just 'hash' a plain text password into the same hash everytime. So you need to consider each hashed password when deciding if the plain text password matches. So looping through each hashed password is necessary, I believe.

Thanks !
