### ISSUE TITLE
Changing password_archiving_count down removed the deny_old_password validation

### ISSUE THREAD

**Issue by jono-booth** [devise-security/devise-security#168]
When changing the setting `password_archiving_count` from say 5 to 1, then the `password_archive_included?` doesn't pick up the older passwords for some reason. If I debug around here I see that it doesn't match up to the expected password and this method returns false.

https://github.com/devise-security/devise-security/blob/master/lib/devise-security/models/password_archivable.rb#L41

**Comment by oniofchaos** [comment]
Are you able to create a test case that demonstrates the issue?

**Comment by jono-booth** [comment]
Thanks for the speedy reply, I am not 100% sure that my title and description are the actual problem, but I am not sure what else to call this. I changed the password archiving count from 5 to 1 and it now allows me to reset my password to the same as my current password.

```ruby
# In my User model
devise :database_authenticatable,
  :registerable,
  :recoverable,
  :rememberable,
  :validatable,
  :password_expirable,
  :password_archivable
```

```ruby
# config/initializers/devise_security.rb

config.expire_password_after = true
config.deny_old_passwords = true

# This was changed from 
# config.password_archiving_count = 5
# config.deny_old_passwords = 5
```

Because of the above change there are 5 passwords in the database but the limit is not 1.
If I pry on line 46 [here](https://github.com/devise-security/devise-security/blob/master/lib/devise-security/models/password_archivable.rb#L46), I only get 2 passwords set in `old_passwords_including_cur_change` none of which match the supplied `password` in my test cases.

**Comment by oniofchaos** [comment]
Your title is fine - also thank you for submitting an issue!

Without having dug into the code - my guess is that once you make the change back to only looking back to one password vs five, the old archived password you're running into is beyond the lookup range and so the validation passes.

If so, that makes sense to me. If the limit is one old password, I don't care what your password was five passwords ago.

If you look at [this method](https://github.com/devise-security/devise-security/blob/master/lib/devise-security/models/password_archivable.rb#L71), it appears that after you run an update (per record) these old passwords will be cleaned out after you change the config. 

Thoughts?

**Comment by jono-booth** [comment]
Looking at the method you linked to those records should not be in my database then. Maybe the problem lies elsewhere, it might not be archiving passwords on my environment for some reason. I am still looking into it, will get back to you. Thanks for the help!

**Comment by jono-booth** [comment]
After some more investigation, it looks some parts of devise are being overridden by another gem we are using called Spree. It's highly likely that the issues lies elsewhere and not in this gem.

I cannot afford to spend anymore time on this issue, but maybe we can close this issue for now and I can start a new one with some more concrete examples when I revisit this.
