### ISSUE TITLE
Could not find generator 'devise_security:install'

### ISSUE THREAD

**Issue by maurosbu** [devise-security/devise-security#17]
Hi,
I'm working on a Rails 5.1 app and I'm trying to configure the devise_security gem, but I have a problem with the generator.

    $ bin/rails g devise_security:install
    Could not find generator 'devise_security:install'. Maybe you meant 'devise_security:install', 'devise:install' or 'draper:install'
    Run `rails generate --help` for more options.

This is what I added to the Gemfile

    gem 'devise', '~> 4.4'
    gem 'devise-security', '~> 0.11.0'
    gem 'rails_email_validator'

Many thanks in advance for your help.

Mauro

**Comment by maurosbu** [comment]
Duplicated of https://github.com/devise-security/devise-security/issues/8
Is it possible to release a new version of the gem?

**Comment by oniofchaos** [comment]
https://github.com/devise-security/devise-security/releases/tag/v0.11.1 is now live on Rubygems

**Comment by natebird** [comment]
@oniofchaos Thanks for releasing. I was working on this today too. :-) I'm working on integrating with CircleCI, Rubocop, and Coveralls to get the codebase a little better structured.

**Comment by oniofchaos** [comment]
Sweeeeeeet
