### ISSUE TITLE
Can valid_email be a replacement for rails_email_validator?

### ISSUE THREAD

**Issue by maurosbu** [devise-security/devise-security#18]
The module **secure_validatable** suggests using the [rails_email_validator](https://rubygems.org/gems/rails_email_validator) gem which seems to be unmaintained (last commit dates back to Jun 16, 2011). Is the gem [valid_email](https://rubygems.org/gems/valid_email) a valid replacement?

Many thanks,
Mauro

**Comment by oniofchaos** [comment]
Honestly the code here is a bit confusing and Rails magic-y but on initial read it looks like yes. They both just require `email: true` in the model. Are you trying to actively use this?

**Comment by natebird** [comment]
I agree. I haven't tried to replace the gem yet but it is convoluted. @maurosbu if you create a PR for this I'd be glad to review it. If not, I'll add it to the list. :-)

**Comment by oniofchaos** [comment]
Closing old issues, if you have more info to contribute please feel free to re-open.
