### ISSUE TITLE
Occasionally getting falsy "Password expired" msg

### ISSUE THREAD

**Issue by yairper** [devise-security/devise-security#186]
Until now we were using `devise_security_extensions` 0.10.0
which had this issue and had been fixed with a fork. 
see commit: https://github.com/OwnBackup/devise_security_extension/commit/3557f8fb01b0d2fee56c47fa6b0a1a32b74e876f#diff-319d340c1a338ea901c51a01e3cc5004

Now we've upgraded to latest `devise_security` and the same code causing us this issue is still there.
In order not to fork again, I've created a patchy rails initializer in our system for now:
```ruby
module PassExpFix                                                                                  
  def []= (k, v)                                                                                   
    Rails.logger.debug "##### warden.sesseion(:user)[#{k.inspect}] = #{v.inspect} ##### has been called"
    if k == :password_expired                                                                      
      k = 'password_expired'
    end 
    super(k, v)                                                                                    
  end
end

module PassExpWardenPatch                                                                          
  def session(scope)
    if scope == :user                                                                              
      instance = super(scope)                                                                      
      instance && instance.extend(PassExpFix)
    else
      super                                                                                        
    end
  end
end

class Warden::Proxy                                                                                
  prepend PassExpWardenPatch
end
```

**Comment by natebird** [comment]
Can you create a failing test case and a PR fix for this issue?

**Comment by yairper** [comment]
I can easily create a PR, not sure what is the use case, from our POV it was random.
reading the code at `lib/devise-security/controllers/helpers.rb::58` 
not sure what makes it go into this `else`
could be that once upon a time it was indifferent hash so it worked?
WDYT?

**Comment by natebird** [comment]
Yeah, it looks like line 51 uses `'password_expired'` and line 58 uses `:password_expired`. I've only taken a cursory look at the code but that stands out as odd. I think it warrants more investigation. That code has tons of `if` and `if not` statements which are also terrible for debugging and understanding use cases and impact.
