### ISSUE TITLE
Password complexity without redirect?

### ISSUE THREAD

**Issue by bhushangahire** [devise-security/devise-security#191]
How can I use password complexity functionality without redirection on the rails app?
I am using Angular and API base rails backend. When the password expires it redirects to rails URL.

**Comment by olbrich** [comment]
If you want to use the password complexity validator, https://github.com/devise-security/devise-security/blob/master/lib/devise-security/validators/password_complexity_validator.rb

Tests for it are found in https://github.com/devise-security/devise-security/blob/master/test/test_complexity_validator.rb 

Not sure I can provide much more help without understanding your application better.

**Comment by oniofchaos** [comment]
Closing this issue since it's old. If you have more details for us to help answer your question, please comment and re-open.
