### ISSUE TITLE
Refactor security_questionable

### ISSUE THREAD

**Issue by olbrich** [devise-security/devise-security#207]

**Comment by kaysiz** [comment]
@tmr08c May you please add a description to issue.

**Comment by tmr08c** [comment]
@kaysiz sorry for the lack of description! Looking at the `SecurtiyQuestionable` module, it actually [looks basically empty](https://github.com/devise-security/devise-security/blob/3e53dd66511feb5fcddb77c706179a81143eef79/lib/devise-security/models/security_questionable.rb#L3-L19), so I'm not sure if we need to do any refactoring. I will update the other refactoring issues with some additional details if you are interested in any of them. 

@olbrich let me know if I missed anything you were hoping to see change/
