### ISSUE TITLE
RSpec deprecation warning message

### ISSUE THREAD

**Issue by samuelvaneck** [devise-security/devise-security#22]
When running RSpec tests with the latest version I'm getting deprecation warning messages:

> DEPRECATION WARNING: The behavior of `attribute_changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute?` instead.

I'm using the following version
- rails: 5.1.4
- devise: 4.3.0
- devise-security: 0.11.1
- rspec: 3.7.0

**Comment by natebird** [comment]
This was introduced in Rails 5.1 and will stop working (from what I can tell) in Rails 6.0. Since we currently support Rails 4.1.x and above the solution will need to support previous versions where the new methods don't exist.

If you have a pull request I'd be glad to review it.

**Comment by samuelvaneck** [comment]
I’ll give it a try. :)

**Comment by mileslane** [comment]
We are seeing this as well. It makes our tests very noisy, so a fix would be much appreciated.

**Comment by samuelvaneck** [comment]
:+1:
