### ISSUE TITLE
Is skip_session_limitable? implemented/overridable?

### ISSUE THREAD

**Issue by rmccown** [devise-security/devise-security#226]
Howdy 
We want to implement session_limitable, and turn it off for a subset of our users.  The code in session_limitable.rb hints that you can override skip_session_limitable?, but so far we havent been able to get it to work, and the Google oracle doesnt provide any insight.  We have been able to override update_unique_session_id! with our own code, so we think we're on the right track. 

Is skip_session_limitable? indeed overridable?

**Comment by tmr08c** [comment]
Hi @rmccown! 

It looks like the functionality to override `skip_session_limitable?` was added in [this PR](https://github.com/devise-security/devise-security/pull/74), but hasn't been added to a release yet. 

@olbrich has it tagged in the [0.15.0 milestone](https://github.com/devise-security/devise-security/milestone/4) which is the next planned release. I don't think there is an expected release for that at the moment though. 

In the meantime, you could try updating your Gemfile to point to the `master` branch or even the [commit hash](https://github.com/devise-security/devise-security/commit/37b720179fc64a25ef308baa9e3badc6bf6e5400) that added the functionality.

**Comment by rmccown** [comment]
Thanks @tmr08c, bundling with the master branch did the trick.

**Comment by tmr08c** [comment]
Excellent to hear, @rmccown! 🎉 

I'm going to go ahead and close the issue. Please feel free to reach out if you run into any other issues.
