### ISSUE TITLE
🎃 Hacktoberfest 2020 

### ISSUE THREAD

**Issue by tmr08c** [devise-security/devise-security#232]
Happy [Hacktoberfest](https://hacktoberfest.digitalocean.com/) everyone! 

# What to work on 

While we have a [few Issues](https://github.com/devise-security/devise-security/issues?q=is%3Aissue+is%3Aopen+label%3AHacktoberfest) that are leveraging the `Hacktoberfest` label, these are not the only way you can help contribute. 

You can also consider:

* Adding or improving our [translations](https://github.com/devise-security/devise-security/tree/master/config/locales) (see #196 and #223 for examples). 
* Addressing [Code Climate issues](https://codeclimate.com/github/devise-security/devise-security/issues).

# How to contribute

Please take a look at our [section on contributing](https://github.com/devise-security/devise-security#contributing-to-devise-security) in the README for help getting started. 

# Getting support 

Feel free to leverage this Issue as a thread for sharing ideas or reaching out for support.

**Comment by dingyifei** [comment]
Hi, can I work on the `zh-CN` translation?

**Comment by tmr08c** [comment]
@dingyifei, yeah, that'd be great!

**Comment by dingyifei** [comment]
#235 Done!

**Comment by oniofchaos** [comment]
Looks like @dingyifei is correct.

https://hacktoberfest.digitalocean.com/hacktoberfest-update

```
PRs count if:
Submitted in a repo with the hacktoberfest topic AND
during the month of October AND (
  The PR is merged OR
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  The PR has been approved
)
```

**Comment by mhi20** [comment]
Hi,
Can I add a `fa` locale?

**Comment by tmr08c** [comment]
Thanks for adding the topic, @oniofchaos!

@mhi20, definitely!

**Comment by tmr08c** [comment]
I hope everyone had a successful Hacktoberfest. A big thank you to everyone that opened up PRs in our project this year!
