### ISSUE TITLE
Rubocop warning on initializer file name

### ISSUE THREAD

**Issue by DevS1993** [devise-security/devise-security#238]
So i recently added this extension to simplify my password validation flow and i noticed this error from Rubucop.

![devise_security_rubocop](https://user-images.githubusercontent.com/21246070/95175297-ea4a4b80-07d8-11eb-816d-da196f369159.png)

Other initializers (like devise_token_auth.rb / filter_parameter_logging.rb) follow snake_case file naming convention.

is the file name `devise-security.rb` intentionally named like this and i have to add an exception to Rubocop config?

**Comment by olbrich** [comment]
I'm pretty sure that rails will load it just fine if you rename the file. Let us know if you have trouble. I would also welcome a PR to make the name more consistent with rubocop.

**Comment by DevS1993** [comment]
Yes @olbrich rails loads it even after changing the file name follow snake_case. No troubles. I'll work on a PR to change the default behavior.

**Comment by tmr08c** [comment]
@DevS1993 I've assigned the Issue to you. Let me know if you would like me to unassign it.

🤔  In the short-term, you may be able to rename the file to `devise_security.rb` in your application. I think the important part is that it will still run `Devise.setup` and let you configure anything you need. The actual file name _shouldn't_ matter.
