### ISSUE TITLE
password_regex and ReDoS attacks

### ISSUE THREAD

**Issue by micapam** [devise-security/devise-security#24]
First of all, thanks for forking the original repo and keeping the functionality alive! 

I'm using devise-security in an app I'm working on. A problem I found is that the `password_regex` setting wasn't usable for my requirements (ensuring passwords include characters from certain classes: e.g. uppercase letter, lowercase letter, a number and a symbol). Whatever regex I tried to accomplish this, I found I was opening the app to a potential ReDos attack:

https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS

Maybe if someone with better regex skills than me could add some examples of safe regexes to the documentation (and warnings of the issue) that would be helpful. 

Alternatively, I'm using a slightly different way of validating complexity in passwords by specifying required character classes in Devise config. I could raise a PR for this if you like. However, it is necessarily a breaking change, as old configs won't work any more. Perhaps (if you like this method) both could be implemented side by side, with the `password_regex` config deprecated until it's phased out...

**Comment by natebird** [comment]
I'd be happy to review a PR of this feature. Thanks for looking into this.
