### ISSUE TITLE
Link broken/down

### ISSUE THREAD

**Issue by DevS1993** [devise-security/devise-security#246]
The external article under the section : **Email validation using the Ruby constant** is broken. I have tried it on numerous days at different times, same result.

![devise_security_email_validation](https://user-images.githubusercontent.com/21246070/95663839-08f56d00-0b60-11eb-9d60-2a4a56bafb5c.png)

Should the link be replaced with another link? (it may go down in the future)

Or should a snippet be added showing how to validate the email using Ruby's inbuilt constant?

**Comment by oniofchaos** [comment]
> Or should a snippet be added showing how to validate the email using Ruby's inbuilt constant?

Yeah let's do that.
