### ISSUE TITLE
Spaces not counted as a symbol/puntuation mark in password_complexity

### ISSUE THREAD

**Issue by MaKalvik** [devise-security/devise-security#281]
It's as the title suggests. I'm wondering if this is expected behaviour or am I missing something?

Is there some specific reason as to why spaces could not be counted as symbols?

The validation works fine if there is another symbol in the password in addition to the space, but not when it's just a space. 

Is there a way to override it?

**Comment by oniofchaos** [comment]
This sounds like a bug to me. I welcome a PR to address it.

**Comment by oniofchaos** [comment]
Thinking about this a little more: implementing this may be difficult because spaces at the beginning/end of a password are often considered user error from copy/paste issues and stripped out. I would only want to allow it if it was in the middle of a password.

Examples:
- "good password" => valid
- "goodpassword " => not valid

**Comment by olbrich** [comment]
(NIST)[https://pages.nist.gov/800-63-3/sp800-63b.html] no longer recommends password complexity rules, and they also specifically mention spaces a few times.

> All printing ASCII [RFC 20] characters as well as the space character SHOULD be acceptable in memorized secrets. Unicode [ISO/ISC 10646] characters SHOULD be accepted as well. To make allowances for likely mistyping, verifiers MAY replace multiple consecutive space characters with a single space character prior to verification, provided that the result is at least 8 characters in length.

> Spaces themselves, however, add little to the complexity of passwords and may introduce usability issues (e.g., the undetected use of two spaces rather than one), so it may be beneficial to remove repeated spaces in typed passwords prior to verification.

Given that spaces don't really add a lot of complexity to passwords, I would not recommend lumping them into the same category as symbols.

As for overriding the existing behavior, you can modify the symbol regex in the `DeviseSecurity::PasswordComplexityValidator` by modifying the `PATTERNS` constant (versions < 0.17) or the `patterns` method in versions >= 0.17.
