### ISSUE TITLE
Add CodeClimate support

### ISSUE THREAD

**Issue by olbrich** [devise-security/devise-security#29]
Codeclimate does a series of checks for code quality.  It would be nice to add code climate support so we can continue to improve the quality of this project.

**Comment by natebird** [comment]
I've used CodeClimate. I think that is a good addition to the project.

**Comment by natebird** [comment]
I'm creating a PR for CodeClimate. Here are the results if you want to browse: https://codeclimate.com/github/devise-security/devise-security
