### ISSUE TITLE
Figure out an easy way to run the test suite locally for all combos of ORM, Ruby, and Rails

### ISSUE THREAD

**Issue by oniofchaos** [devise-security/devise-security#293]
Probably using commands involved with the `appraisal` gem that we already use https://github.com/thoughtbot/appraisal

**Comment by olbrich** [comment]
I've tried using https://github.com/nektos/act with not a whole lot of luck. It doesn't seem to play well with build matrices.

**Comment by oniofchaos** [comment]
Tried out that tool and I had the same issue with the build matrices. The output was also super verbose. I think the best bet is going to be for users to push their code to their own forked repos and check out the build results there.
