### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dsounded** [devise-security/devise-security#297]
Hi, guys. Thanks for the great job!

I'd like to know the new release date. Since this change https://github.com/devise-security/devise-security/commit/e280f147dcd43a70e3fecbe8e12c09911fd17539#diff-80cfb2fb1849d9a2fd2fbad3821ff00c7d0d22e3ea1a095f9d9acf59c1ef2db8

is really important for `Ruby 3.0`

**Comment by oniofchaos** [comment]
I'll take a look and see if things are ready. There were some changes I wanted to get into the next release but they possibly can wait so that this fix goes out.

**Comment by oniofchaos** [comment]
Once we get https://github.com/devise-security/devise-security/pull/291 and https://github.com/devise-security/devise-security/pull/300 in we should be able to do a release.

**Comment by StefanRitchie** [comment]
Seconding the OP - thanks for the great work, but also my app requires `Ruby 3.0`, and so also requires this new release.

Many thanks

**Comment by oniofchaos** [comment]
v0.16.0 is out.
