### ISSUE TITLE
How to properly update copyright notice?

### ISSUE THREAD

**Issue by dillonwelch** [devise-security/devise-security#301]
https://github.com/devise-security/devise-security#copyright

We've forked from the project that the individual was maintaining. Do we remove the name? Do we just keep the year updated. Honestly not sure.

cc: @devise-security/maintainers

**Comment by natebird** [comment]
I'm not 100% sure what to do either but this StackOverflow post helps a little bit. It is about the GPL but MIT is even more lenient.

https://stackoverflow.com/questions/4475319/how-to-rebrand-copyright-a-forked-project-gnu-gpl

From the post, I would recommend adding a copyright notice above the original author's copyright. So in essence it would look like this:

```
Copyright (c) 2011-2017 Marco Scholl. 2017-2021 Dillion Welch. See LICENSE.txt for further details.
```

And update the LICENSE.txt with the same.

```
Copyright (c) 2017 Dillion Welch
Copyright (c) 2011 Marco Scholl

Permission is hereby granted, free of charge, to any person obtaining
...
...
```

Whether all the maintainers' names are included is another discussion point. I don't really care either way. You all have done much more work on this project than I have. 🤣
