### ISSUE TITLE
Audit what gems of Rails we depend on and add them as dependencies

### ISSUE THREAD

**Issue by oniofchaos** [devise-security/devise-security#311]
With https://github.com/devise-security/devise-security/releases/tag/v0.16.0, we have removed support for Rails 4.2. However, we do not have any direct dependencies on Rails or any of its gems. We get a dependency on `railties` thanks to `devise`, but for the version we are on are very permissive and allow 4.1+. This would technically allow someone on Rails 4.2 to update to 0.16.0 and have a gem that's not functional.

In local development, we pull in all of Rails due to the `easy-captcha` gem. This has masked the above issue. 

We should explicitly state which gems of Rails we depend on and ensure their version requirements match what we test for.

**Comment by olbrich** [comment]
Well, `activerecord` for sure, and probably `activesupport`.
