### ISSUE TITLE
Password length/complexity/etc errors returned when password is blank

### ISSUE THREAD

**Issue by TalonGrayson** [devise-security/devise-security#322]
If my user tries to submit the sign up form without a password present, the following errors are returned (obviously the exact messages are dependant on config):

```Ruby
0> resource.errors[:password]
0> ["can't be blank", "is too short (minimum is 8 characters)", "must contain at least one digit", "must contain at least one lower-case letter", "must contain at least one punctuation mark or symbol", "must contain at least one upper-case letter"]
```

I concede that the errors are all accurate and relevant, but to me it feels like the first error negates the need to display the subsequent errors. I also concede that not everyone will want the subsequent errors filtered by the validator.

Is there a way to config this to my preference, or will I need to write a smelly filter?

**Comment by oniofchaos** [comment]
Sadly there is no way to configure it right now. I do agree that it's a lot of errors when just the first would be fine.

Can you make the field required for form submission on your HTML or JS?

**Comment by TalonGrayson** [comment]
Apologies for the late reply.

Requiring the field in HTML is what I've ended up doing, which works but is very browser dependant and a little front-end heavy to be really robust. It feels like a workaround rather than a solution, but it's better than it was... the backend checks will still get hit in prod if frontend fails to catch any validation issues, so there's that :)
