### ISSUE TITLE
allow_passwords_equal_to_email config greatly slows down User validation

### ISSUE THREAD

**Issue by dillonwelch** [devise-security/devise-security#349]
See https://github.com/devise-security/devise-security/pull/277#issuecomment-973099879

**Comment by dillonwelch** [comment]
@tiagotex I was able to reproduce the slowdown you noticed. It looks like it is related to the strategy used of creating a duplicated User model and setting the password on it, an operation that takes some time. I'm looking into how we can do this validation without going through that process.

**Comment by dillonwelch** [comment]
@tiagotex I do see significant improvement in the test suite when I use an alternative method of validating the password (from 92s to 56s).

Can you try out this branch and see if it fixes the issue for you? https://github.com/dillonwelch/devise-security/tree/fix-user-perf

**Comment by tiagotex** [comment]
Hi @dillonwelch 

Thank you so much for taking the time to address this 💚

I will test it tomorrow and will share the results here.

**Comment by tiagotex** [comment]
@dillonwelch Can confirm this fixes the perfomance regression 🙌

**Comment by dillonwelch** [comment]
Great, will work in polishing off when I can.
