### ISSUE TITLE
Support Mongoid

### ISSUE THREAD

**Issue by natebird** [devise-security/devise-security#36]
Is it worth supporting Mongoid? Devise supports it.

**Comment by oniofchaos** [comment]
I personally don't think so. At best, it would be in a separate gem.

**Comment by olbrich** [comment]
I don't have a sense of how much people even use mongoid.  I might be willing to investigate it if a lot of users expressed an interest.

**Comment by scicco** [comment]
+1 
We are currently using Mongoid with devise and adding devise-security features into our application will help us a lot to be compliant with GDPR requirements.

**Comment by brunoporto** [comment]
https://github.com/devise-security/devise-security/pull/43

**Comment by DBDeveloper87** [comment]
I am beginning my app development on Active Record ORM, but am also learning how to work with MongoDB at the same time.  I do not yet understand MongoDB enough to use it properly, however its capabilities are in line with plans for future development of my application, so I plan to switch ORMs then.
For now, I'll use Devise-Security; however, when I make the switch to mongoID if this gem doesn't yet support it, I will need some alternative for the features you have in your gem.

**Comment by scicco** [comment]
Please take a look at #76 . If someone can review my work and help fixing the failing test.

**Comment by olbrich** [comment]
@scicco what version of Devise and Mongoid are you using?

**Comment by scicco** [comment]
Hello @olbrich, this is taken from my old Gemfile.lock (I didn't pull the latest changes)

```
  ...
    mongoid (7.0.2)
      activemodel (>= 5.1, < 6.0.0)
      mongo (>= 2.5.1, < 3.0.0)
  ...
    devise (4.6.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 6.0)
      responders
      warden (~> 1.2.3)
  ...
```
