### ISSUE TITLE
Use main instead of master

### ISSUE THREAD

**Issue by dillonwelch** [devise-security/devise-security#405]

**Comment by alec-c4** [comment]
What's wrong with master?

**Comment by natebird** [comment]
I've created a `main` branch off of master. Do we need to merge/close any PRs before making this change in the project?

**Comment by dillonwelch** [comment]
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch looks like this was just a Github setting - ez!
