### ISSUE TITLE
not working with the latest release of devise

### ISSUE THREAD

**Issue by francescob** [devise-security/devise-security#413]
in latest release of devise the method activerecord51? in Devise module was removed/renamed, thus breaking this gem

**Comment by rocket-turtle** [comment]
devise 4.9.2 has a Deprecation now. 

```
gems/devise-security-0.17.0/lib/devise-security/models/compatibility/active_record_patch.rb:9:in `<module:ActiveRecordPatch>': DEPRECATION WARNING: [Devise] `Devise.activerecord51?` is deprecated and will be removed in the next major version. (ActiveSupport::DeprecationException)
It is a non-public method that's no longer used internally, but that other libraries have been relying on.
```

@dillonwelch 
could you release a new version with this "fix" - https://github.com/devise-security/devise-security/pull/415/files

If your interested in dropping older Rails Versions I can have a look at it and give it a shot. Just let me know.

**Comment by dillonwelch** [comment]
@olbrich thanks for taking care of this one
