### ISSUE TITLE
pwned_password

### ISSUE THREAD

**Issue by alec-c4** [devise-security/devise-security#422]
Hey!
It looks like https://github.com/michaelbanfield/devise-pwned_password is not maintained anymore, so what about to copy their functionality in your gem?

**Comment by dillonwelch** [comment]
![Screenshot 2023-08-23 at 4 13 12 PM](https://github.com/devise-security/devise-security/assets/1635820/6c62ccf8-1003-4b69-b868-04bb63f7724d)

While they have not released an updated version, there does appear to be some activity from a few months ago.
