### ISSUE TITLE
Why Validate Email Uniqueness?

### ISSUE THREAD

**Issue by MattKitmanLabs** [devise-security/devise-security#424]
Why are we validating email uniqueness here?

https://github.com/devise-security/devise-security/blame/29ac90938436471498353328b61ee82d3e946341/lib/devise-security/models/secure_validatable.rb#L44

 If the email is not one of the authentication_keys, then maybe it should be down to the developers on each individual project to manage how they validate the email and within what scope.

Any thoughts or feedback on this?

**Comment by dillonwelch** [comment]
Can you elaborate on why someone would want multiple users to share an email address?

We could add a `email_uniqueness_required?` method and set it to true by default, and then the dev could override as desired.
