### ISSUE TITLE
Missing 'required_fields' method within devise extensions

### ISSUE THREAD

**Issue by stengineering0** [devise-security/devise-security#436]
There is built-in `Devise::Models.check_fields! Model` method which checks for required DB columns per enabled Devise extension for the Model class. Under the hood it tries to call 'required_fields' method for extension module (such as `Devise::Models::PasswordArchivable` or whatever).

At the moment it raises `NoMethodError` or deprecation warning (since https://github.com/heartcombo/devise/pull/1697) against `devise-security` extensions. Might be fixed like:

```ruby
module Devise
  module Models
    module PasswordArchivable
      def self.required_fields(klass)
        []
      end
    end
  end
end

```

**Comment by dillonwelch** [comment]
Thanks for the report!

**Comment by ayerdines** [comment]
Hi guys!! I would like to work on this, can I go ahead with the changes?

**Comment by dillonwelch** [comment]
Go for it! Tag me for a review when you make the PR.

**Comment by ayerdines** [comment]
@dillonwelch I have created a PR. It looks like I can't select reviewers in the PR, please help me review it.
Thank you!!
