### ISSUE TITLE
Fix Deprecation warning -- Support Rails >= 5

### ISSUE THREAD

**Issue by SauloSilva** [devise-security/devise-security#44]
DEPRECATION WARNING: The behavior of `attribute_changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute?` instead.

This warning is [here](https://github.com/devise-security/devise-security/blob/master/lib/devise-security/models/password_expirable.rb#L53).

**Comment by olbrich** [comment]
@SauloSilva How did you get that deprecation warning?  There is only a `before_save` callback in that code, not the `after_save` callback the message describes.
