### ISSUE TITLE
Drop support for EOL versions of Ruby and Rails

### ISSUE THREAD

**Issue by olivier-thatch** [devise-security/devise-security#450]
Hi,

I am working on a PR that adds newer Rails versions (7.1 and 7.2) to CI.

While working on this I realized that the matrix of Ruby and RoR versions is becoming quite unwieldy due to the large number of versions currently supported:
* Ruby: 2.7, 3.0, 3.1, 3.2, 3.3
* Rails: 5.2, 6.0, 6.1, 7.0, and now 7.1 and 7.2

I am also running into compatibility issues with some of the dependencies, e.g. sqlite3 dropped support for Ruby 2.7 in its 2.0 release.

According to endoflife.date, Ruby 2.7 and 3.0 have reached EOL and no longer receive any updates (including security updates): https://endoflife.date/ruby

Similarly, Rails 5.2 and 6.0 have reached EOL, and 6.1 will reach EOL very soon: https://endoflife.date/rails

Would the maintainers be okay with dropping support for all these versions? The remaining matrix would look like this:
* Ruby: 3.1, 3.2, 3.3
* Rails: 7.0, 7.1, 7.2

cc @dillonwelch @olbrich

**Comment by dillonwelch** [comment]
That sounds reasonable to me.

**Comment by olbrich** [comment]
It's also in keeping with the maintenance policy outlined in our README.  Thanks for looking into this @olivier-thatch

**Comment by dillonwelch** [comment]
Partially completed via https://github.com/devise-security/devise-security/pull/451

**Comment by olbrich** [comment]
Fixed in #454
