### ISSUE TITLE
Process to Reset User Locked Out Due to Inactivity

### ISSUE THREAD

**Issue by garyfoster** [devise-security/devise-security#50]
What is the process to unlock a user? Each time this has happened, I notice that the expired_at field in the db for the affected user is nil. I would assume that would have a date/time that I need to clear out to unlock so not sure why it's nil. If I set the last_activity_at to a recent date, that allows the user to sign in, but something doesn't seem right with this. It's easily worked around but figured I'd ask in case I'm missing something, or if this is a bug. I can provide more details if needed.

**Comment by olbrich** [comment]
IIRC, the lockout due to inactivity is driven by the `last_activity_at` attribute.  Setting the time to now will clear the lock.

**Comment by garyfoster** [comment]
Ok thanks, that is what I've been doing. I was confused as to the purpose of expired_at since it did not have a value for the users that were expired. Looking at the code I'm seeing comments that it can be used for manually setting and is not automatically set. Seems strange, but not entirely unreasonable. Closing this issue..
