### ISSUE TITLE
Could not find generator 'devise_security:install' on Windows 10

### ISSUE THREAD

**Issue by Firebeam** [devise-security/devise-security#8]
Hello. I get this error right after running `bundle install` (I'm not sure if having to work around an issue with bcrypt on Windows has to do with this). The thing is, I can't run the generator right after installing the gem:

`#>rails generate devise_security:install
Could not find generator 'devise_security:install'. Maybe you meant 'devise_security:install', 'devise:install' or 'responders:install'
Run `rails generate --help` for more options.`

These are my gems:

`*** LOCAL GEMS ***

actioncable (5.1.4, 5.1.3, 5.0.1)
actionmailer (5.1.4, 5.1.3, 5.0.1)
actionpack (5.1.4, 5.1.3, 5.0.1)
actionview (5.1.4, 5.1.3, 5.0.1)
activejob (5.1.4, 5.1.3, 5.0.1)
activemodel (5.1.4, 5.1.3, 5.0.1)
activerecord (5.1.4, 5.1.3, 5.0.1)
activerecord-sqlserver-adapter (5.1.1)
activesupport (5.1.4, 5.1.3, 5.0.1)
addressable (2.5.2)
arel (8.0.0, 7.1.4)
ast (2.3.0)
autoprefixer-rails (7.1.6)
bcrypt (3.1.11 x86-mingw32)
bigdecimal (1.2.8)
bindex (0.5.0)
bootstrap (4.0.0.beta2.1)
builder (3.2.3)
bundler (1.15.3)
byebug (9.1.0)
capybara (2.15.4)
childprocess (0.8.0)
ckeditor (4.2.4)
climate_control (0.2.0)
cocaine (0.5.8)
coffee-rails (4.2.2, 4.2.1)
coffee-script (2.4.1)
coffee-script-source (1.12.2)
concurrent-ruby (1.0.5, 1.0.4)
crass (1.0.2)
debase (0.2.2.beta10, 0.2.1)
debase-ruby_core_source (0.10.0)
debug_inspector (0.0.2)
devise (4.3.0)
devise-security (0.11.0)
did_you_mean (1.0.0)
erubi (1.7.0, 1.6.1)
erubis (2.7.0)
execjs (2.7.0)
ffi (1.9.18 x86-mingw32)
globalid (0.4.1, 0.4.0, 0.3.7)
i18n (0.9.1, 0.9.0, 0.8.6, 0.7.0)
io-console (0.4.5)
jbuilder (2.7.0, 2.6.1)
jquery-rails (4.3.1, 4.2.2)
jquery-ui-rails (6.0.1)
json (1.8.3)
loofah (2.1.1, 2.0.3)
mail (2.7.0, 2.6.6, 2.6.4)
method_source (0.9.0, 0.8.2)
mime-types (3.1)
mime-types-data (3.2016.0521)
mimemagic (0.3.2)
mini_mime (1.0.0, 0.1.4)
mini_portile2 (2.3.0, 2.1.0)
minitest (5.10.3, 5.10.1, 5.8.5)
multi_json (1.12.2, 1.12.1)
net-telnet (0.1.1)
nio4r (2.1.0, 1.2.1)
nokogiri (1.8.1 x86-mingw32, 1.7.0.1 x86-mingw32)
orm_adapter (0.5.0)
paperclip (5.1.0)
parallel (1.12.0)
parser (2.4.0.0)
pg (0.21.0 x86-mingw32)
popper_js (1.12.5)
power_assert (0.2.6)
powerpack (0.1.1)
psych (2.1.0)
public_suffix (3.0.1, 3.0.0)
puma (3.10.0, 3.6.2)
rack (2.0.3, 2.0.1)
rack-test (0.7.0, 0.6.3)
rails (5.1.4, 5.1.3, 5.0.1)
rails-dom-testing (2.0.3, 2.0.2)
rails-html-sanitizer (1.0.3)
railties (5.1.4, 5.1.3, 5.0.1)
rainbow (2.2.2)
rake (12.2.1, 12.1.0, 12.0.0, 10.4.2)
rb-fsevent (0.10.2)
rb-inotify (0.9.10)
rb-readline (0.5.5)
rdoc (4.2.1)
responders (2.4.0)
rubocop (0.50.0)
ruby-debug-ide (0.6.1.beta9)
ruby-progressbar (1.9.0)
rubyzip (1.2.1)
sass (3.5.3, 3.5.2, 3.5.1, 3.4.23)
sass-listen (4.0.0)
sass-rails (5.0.6)
selenium-webdriver (3.7.0, 3.6.0)
sprockets (3.7.1)
sprockets-rails (3.2.1, 3.2.0)
sqlite3 (1.3.13 x86-mingw32)
sqlite3-ruby (1.3.3)
test-unit (3.1.5)
thor (0.20.0, 0.19.4)
thread_safe (0.3.6, 0.3.5)
tilt (2.0.8, 2.0.5)
tiny_tds (2.0.0 x86-mingw32)
tinymce-rails (4.7.2)
turbolinks (5.0.1)
turbolinks-source (5.0.3, 5.0.0)
tzinfo (1.2.4, 1.2.3, 1.2.2)
tzinfo-data (1.2017.3, 1.2017.2, 1.2016.10)
uglifier (3.2.0, 3.0.4)
unicode-display_width (1.3.0)
warden (1.2.7)
web-console (3.5.1, 3.4.0)
websocket-driver (0.6.5, 0.6.4)
websocket-extensions (0.1.2)
xpath (2.1.0)`

**Comment by Firebeam** [comment]
Problem is fixed in the latest gem from master. Should I close this?

**Comment by natebird** [comment]
Yes. I’ll close it.
