### ISSUE TITLE
password_archivable - Possible to use time frame rather than number?

### ISSUE THREAD

**Issue by mattgrande** [devise-security/devise-security#82]
I have a requirement that passwords cannot be reused if they have been used in the last year. From what I can tell, `password_archivable` only allows you to check against the previous _count_ of passwords.

1. Is this correct?
2. Does `devise-security` have the feature I'm looking for?
3. If not, would you be open to a PR if I end up needing to implement it?

**Comment by natebird** [comment]
As a workaround, you could use a combination of the number of passwords and the length of time before a password is expired to get to a year.

Example: Passwords expire after 90 days and you can't reuse the last 4 passwords. That would put you over a year.

**Comment by mattgrande** [comment]
Yep, that's probably what I'm going to do.
