### ISSUE TITLE
Error when config.eager_load = true

### ISSUE THREAD

**Issue by seanmsmith23** [devise-security/devise-security#90]
Ruby 2.4.5 and Rails 5.0.

Getting `in skip_callback': Before process_action callback :handle_password_change has not been defined (ArgumentError)` when trying to start my server. It seems like that method is being lazy loaded, but with Rails 5 it errors if the method has not yet been defined [as per this thread](https://github.com/lynndylanhurley/devise_token_auth/issues/500). 

It doesn't seem like others are experiencing this issue with this gem, any help would be appreciated.

**Comment by seanmsmith23** [comment]
Just to flesh this out a bit more. Here's the line within the gem that creates the error: https://github.com/devise-security/devise-security/blob/master/app/controllers/devise/password_expired_controller.rb#L4

Here's where that method is defined: https://github.com/devise-security/devise-security/blob/5f06e98907aa93a2ebd190a82725b261bdf7f091/lib/devise-security/controllers/helpers.rb#L46

Here is where it's indicating it should be lazyloaded: https://github.com/devise-security/devise-security/blob/5f06e98907aa93a2ebd190a82725b261bdf7f091/lib/devise-security/rails.rb#L6

**Comment by oniofchaos** [comment]
Are you able to reproduce this with a dummy app?

**Comment by longkt90** [comment]
From rails 5,  `skip_before_action :handle_password_change` would raise ArgumentError it it's not defined. we can change to `skip_before_action :handle_password_change, raise: false`

reference: https://github.com/rails/rails/pull/19029

**Comment by oniofchaos** [comment]
Going to close due to inactivity. Feel free to comment with a dummy app to re-open.
