### ISSUE TITLE
Getting "uninitialized constant DEVISE_ORM" during install

### ISSUE THREAD

**Issue by Sh1ken** [devise-security/devise-security#99]
Hey,

While trying to install this gem I'm getting the following error message during `rails generate devise_security:install` using devise-security 0.14.0:

 `.../lib/devise-security.rb:3:in <top (required)>: uninitialized constant DEVISE_ORM (NameError)`

Currently I'm using devise 4.6.1, rails 5.2.2.1 and activerecord 5.2.2.1. I've been using Devise without any problem and, as far as I know, ActiveRecord should be the default ORM.

I tried to pass `DEVISE_ORM` as an environment variable and defining it on an initializer. Neither of those worked as intended for the install process.

Any suggestions?

**Comment by olbrich** [comment]
@Sh1ken 
This does look like a bug, sorry.

This workaround may help... try defining `DEVISE_ORM=:active_record` in `application.rb` near the top (before the `Bundler.require`).

**Comment by Sh1ken** [comment]
That did the trick! Thanks!

**Comment by Sh1ken** [comment]
@olbrich That did the trick! Thanks.

**Comment by olbrich** [comment]
@Sh1ken Can you try the branch for #100 and see if that fixes the problem without having to force the definition?

**Comment by Sh1ken** [comment]
@olbrich Just tried it. It's working as intended. Thanks for the quick support!

**Comment by shaicoleman** [comment]
Can you please push a new bugfix release?

**Comment by olbrich** [comment]
@shaicoleman Yes.

**Comment by olbrich** [comment]
@shaicoleman done
